using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ProjectService.Data.Migrations
{
    /// <inheritdoc />
    public partial class InitialProjectSchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "Projects" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Name" character varying(200) NOT NULL,
                    "Description" character varying(2000) NOT NULL,
                    "CreatedById" integer NOT NULL,
                    CONSTRAINT "PK_Projects" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "ProjectMembers" (
                    "ProjectId" integer NOT NULL,
                    "UserId" integer NOT NULL,
                    "Role" text NOT NULL DEFAULT 'member',
                    CONSTRAINT "PK_ProjectMembers" PRIMARY KEY ("ProjectId", "UserId"),
                    CONSTRAINT "FK_ProjectMembers_Projects_ProjectId"
                        FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE CASCADE
                );

                ALTER TABLE "ProjectMembers"
                    ADD COLUMN IF NOT EXISTS "Role" text NOT NULL DEFAULT 'member';

                CREATE INDEX IF NOT EXISTS "IX_ProjectMembers_UserId"
                    ON "ProjectMembers" ("UserId");

                UPDATE "ProjectMembers"
                SET "Role" = 'admin'
                WHERE "Role" = 'member'
                  AND ("ProjectId", "UserId") IN (
                      SELECT "Id", "CreatedById"
                      FROM "Projects"
                      WHERE "CreatedById" > 0
                  );

                INSERT INTO "ProjectMembers" ("ProjectId", "UserId", "Role")
                SELECT "Id", "CreatedById", 'admin'
                FROM "Projects"
                WHERE "CreatedById" > 0
                ON CONFLICT DO NOTHING;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ProjectMembers");

            migrationBuilder.DropTable(
                name: "Projects");
        }
    }
}
